# .github/workflows/main.yml

name: build
permissions: {} # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions
on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    if: ${{ (github.repository == 'gattjoe/OCSPChecker') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2
      - name: Set up Python 3.x
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # tag=v5.4.0
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install build twine
      - name: Build pypy package
        run: |
          python -m build
      - name: Check package
        run: |
          twine check dist/*
      - name: Store the distribution packages
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # tag=v4.6.1
        with:
          name: python-package-distributions
          path: dist/
      - name: Attest
        uses: actions/attest-build-provenance@bd77c077858b8d561b7a36cbe48ef4cc642ca39d # tag=v2.2.2
        with:
          subject-path: '${{ github.workspace }}/dist'

  publish:
    if: ${{ (github.repository == 'gattjoe/OCSPChecker') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/p/ocsp-checker
    steps:
    - name: Download the distribution package
      uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # tag=v4.1.9
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # tag=v1.12.4
      with:
        verbose: true